version: '3.8'

volumes:
  kafka_data:
    name: kafka_data
  zookeeper_data:
    name: zookeeper_data

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    expose:
      - '32181'
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
    volumes:
      - 'zookeeper_data:/etc/kafka'
    networks:
      - kafka_network

  kafka:
    image: confluentinc/cp-kafka
    restart: on-failure
    ports:
      - '9092:9092'
    expose:
      - '9093'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    volumes:
      - 'kafka_data:/etc/kafka'
    networks:
      - kafka_network

  # http://localhost:8082
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - '8082:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=default
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9093
    depends_on:
      - kafka
    networks:
      - kafka_network

networks:
  kafka_network:
