version: '3.8'

services:
  pd-spark:
    build:
      context: ./spark
    ports:
      - '4040:4040'
      - '15002:15002'
    volumes:
      - ./spark/propaganda-model.keras:/etc/propaganda-model.keras
    networks:
      - pd-spark_network
      - pd-kafka_network

networks:
  pd-spark_network:
