version: '3.8'

services:
  pd-spark:
    image: bitnami/spark:3.5.0
    command: ['sh', '/etc/entrypoint.sh']
    ports:
      - '4040:4040'
      - '15002:15002'
    volumes:
      - ./spark/entrypoint.sh:/etc/entrypoint.sh
    networks:
      - pd-spark_network
      - pd-kafka_network

networks:
  pd-spark_network:
