version: '3.1'

services:
  telegram-bot:
    image: telegram-bot
    environment:
      TELEGRAM_API_KEY: ${TELEGRAM_API_KEY}
      KAFKA_HOST: kafka
      KAFKA_PORT: 9093
      KAFKA_TOPIC: messages
    depends_on:
      - kafka
    networks:
      - kafka_network