version: '3.8'

services:
  pd-telegram-bot:
    image: telegram-bot
    environment:
      TELEGRAM_API_KEY: ${TELEGRAM_API_KEY:-}
      KAFKA_HOST: pd-kafka
      KAFKA_PORT: 9093
      KAFKA_TOPIC: messages
    depends_on:
      - pd-kafka
    networks:
      - pd-kafka_network
