name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
          
  build_telegram_bot_image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/publishers/telegram_bot
    permissions:
      packages: write
    steps:

      - name: Set up checkout
        uses: actions/checkout@v2
      
      - name: Login to the GitHub registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./src/publishers/telegram_bot
          push: true
          tags: ghcr.io/denisiomytnysiano/prodet-telegram-bot:latest